//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_AutoGenControllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresler
    {
        public int ID { get; set; }
        public string AdresTanimi { get; set; }
        public Nullable<int> Kisi_ID { get; set; }
    
        public virtual Kisiler Kisiler { get; set; }
    }
}
